name: Devops CICI PIPELINE

on:
  push:
    branches:
      - qa
    paths:
      - client/**
      - server/**
      - .github/workflows/QA-CICD.yml

jobs:
  gitleaks-scan:
    name: Gitleaks Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

